# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/chiemsee/clion-2018.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/chiemsee/clion-2018.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chiemsee/Desktop/elka/proi/3prj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chiemsee/Desktop/elka/proi/3prj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/chiemsee/clion-2018.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/chiemsee/clion-2018.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chiemsee/Desktop/elka/proi/3prj/CMakeFiles /home/chiemsee/Desktop/elka/proi/3prj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chiemsee/Desktop/elka/proi/3prj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3prj

# Build rule for target.
3prj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3prj
.PHONY : 3prj

# fast build rule for target.
3prj/fast:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/build
.PHONY : 3prj/fast

Agricultural.o: Agricultural.cpp.o

.PHONY : Agricultural.o

# target to build an object file
Agricultural.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Agricultural.cpp.o
.PHONY : Agricultural.cpp.o

Agricultural.i: Agricultural.cpp.i

.PHONY : Agricultural.i

# target to preprocess a source file
Agricultural.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Agricultural.cpp.i
.PHONY : Agricultural.cpp.i

Agricultural.s: Agricultural.cpp.s

.PHONY : Agricultural.s

# target to generate assembly for a file
Agricultural.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Agricultural.cpp.s
.PHONY : Agricultural.cpp.s

Bus.o: Bus.cpp.o

.PHONY : Bus.o

# target to build an object file
Bus.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Bus.cpp.o
.PHONY : Bus.cpp.o

Bus.i: Bus.cpp.i

.PHONY : Bus.i

# target to preprocess a source file
Bus.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Bus.cpp.i
.PHONY : Bus.cpp.i

Bus.s: Bus.cpp.s

.PHONY : Bus.s

# target to generate assembly for a file
Bus.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Bus.cpp.s
.PHONY : Bus.cpp.s

Company.o: Company.cpp.o

.PHONY : Company.o

# target to build an object file
Company.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Company.cpp.o
.PHONY : Company.cpp.o

Company.i: Company.cpp.i

.PHONY : Company.i

# target to preprocess a source file
Company.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Company.cpp.i
.PHONY : Company.cpp.i

Company.s: Company.cpp.s

.PHONY : Company.s

# target to generate assembly for a file
Company.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Company.cpp.s
.PHONY : Company.cpp.s

Coownership.o: Coownership.cpp.o

.PHONY : Coownership.o

# target to build an object file
Coownership.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Coownership.cpp.o
.PHONY : Coownership.cpp.o

Coownership.i: Coownership.cpp.i

.PHONY : Coownership.i

# target to preprocess a source file
Coownership.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Coownership.cpp.i
.PHONY : Coownership.cpp.i

Coownership.s: Coownership.cpp.s

.PHONY : Coownership.s

# target to generate assembly for a file
Coownership.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Coownership.cpp.s
.PHONY : Coownership.cpp.s

Database.o: Database.cpp.o

.PHONY : Database.o

# target to build an object file
Database.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Database.cpp.o
.PHONY : Database.cpp.o

Database.i: Database.cpp.i

.PHONY : Database.i

# target to preprocess a source file
Database.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Database.cpp.i
.PHONY : Database.cpp.i

Database.s: Database.cpp.s

.PHONY : Database.s

# target to generate assembly for a file
Database.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Database.cpp.s
.PHONY : Database.cpp.s

ElectricCar.o: ElectricCar.cpp.o

.PHONY : ElectricCar.o

# target to build an object file
ElectricCar.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricCar.cpp.o
.PHONY : ElectricCar.cpp.o

ElectricCar.i: ElectricCar.cpp.i

.PHONY : ElectricCar.i

# target to preprocess a source file
ElectricCar.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricCar.cpp.i
.PHONY : ElectricCar.cpp.i

ElectricCar.s: ElectricCar.cpp.s

.PHONY : ElectricCar.s

# target to generate assembly for a file
ElectricCar.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricCar.cpp.s
.PHONY : ElectricCar.cpp.s

ElectricMotorcycle.o: ElectricMotorcycle.cpp.o

.PHONY : ElectricMotorcycle.o

# target to build an object file
ElectricMotorcycle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricMotorcycle.cpp.o
.PHONY : ElectricMotorcycle.cpp.o

ElectricMotorcycle.i: ElectricMotorcycle.cpp.i

.PHONY : ElectricMotorcycle.i

# target to preprocess a source file
ElectricMotorcycle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricMotorcycle.cpp.i
.PHONY : ElectricMotorcycle.cpp.i

ElectricMotorcycle.s: ElectricMotorcycle.cpp.s

.PHONY : ElectricMotorcycle.s

# target to generate assembly for a file
ElectricMotorcycle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricMotorcycle.cpp.s
.PHONY : ElectricMotorcycle.cpp.s

ElectricVehicle.o: ElectricVehicle.cpp.o

.PHONY : ElectricVehicle.o

# target to build an object file
ElectricVehicle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricVehicle.cpp.o
.PHONY : ElectricVehicle.cpp.o

ElectricVehicle.i: ElectricVehicle.cpp.i

.PHONY : ElectricVehicle.i

# target to preprocess a source file
ElectricVehicle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricVehicle.cpp.i
.PHONY : ElectricVehicle.cpp.i

ElectricVehicle.s: ElectricVehicle.cpp.s

.PHONY : ElectricVehicle.s

# target to generate assembly for a file
ElectricVehicle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/ElectricVehicle.cpp.s
.PHONY : ElectricVehicle.cpp.s

FuelCar.o: FuelCar.cpp.o

.PHONY : FuelCar.o

# target to build an object file
FuelCar.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelCar.cpp.o
.PHONY : FuelCar.cpp.o

FuelCar.i: FuelCar.cpp.i

.PHONY : FuelCar.i

# target to preprocess a source file
FuelCar.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelCar.cpp.i
.PHONY : FuelCar.cpp.i

FuelCar.s: FuelCar.cpp.s

.PHONY : FuelCar.s

# target to generate assembly for a file
FuelCar.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelCar.cpp.s
.PHONY : FuelCar.cpp.s

FuelMotorcycle.o: FuelMotorcycle.cpp.o

.PHONY : FuelMotorcycle.o

# target to build an object file
FuelMotorcycle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelMotorcycle.cpp.o
.PHONY : FuelMotorcycle.cpp.o

FuelMotorcycle.i: FuelMotorcycle.cpp.i

.PHONY : FuelMotorcycle.i

# target to preprocess a source file
FuelMotorcycle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelMotorcycle.cpp.i
.PHONY : FuelMotorcycle.cpp.i

FuelMotorcycle.s: FuelMotorcycle.cpp.s

.PHONY : FuelMotorcycle.s

# target to generate assembly for a file
FuelMotorcycle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelMotorcycle.cpp.s
.PHONY : FuelMotorcycle.cpp.s

FuelVehicle.o: FuelVehicle.cpp.o

.PHONY : FuelVehicle.o

# target to build an object file
FuelVehicle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelVehicle.cpp.o
.PHONY : FuelVehicle.cpp.o

FuelVehicle.i: FuelVehicle.cpp.i

.PHONY : FuelVehicle.i

# target to preprocess a source file
FuelVehicle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelVehicle.cpp.i
.PHONY : FuelVehicle.cpp.i

FuelVehicle.s: FuelVehicle.cpp.s

.PHONY : FuelVehicle.s

# target to generate assembly for a file
FuelVehicle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/FuelVehicle.cpp.s
.PHONY : FuelVehicle.cpp.s

Litter.o: Litter.cpp.o

.PHONY : Litter.o

# target to build an object file
Litter.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Litter.cpp.o
.PHONY : Litter.cpp.o

Litter.i: Litter.cpp.i

.PHONY : Litter.i

# target to preprocess a source file
Litter.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Litter.cpp.i
.PHONY : Litter.cpp.i

Litter.s: Litter.cpp.s

.PHONY : Litter.s

# target to generate assembly for a file
Litter.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Litter.cpp.s
.PHONY : Litter.cpp.s

Military.o: Military.cpp.o

.PHONY : Military.o

# target to build an object file
Military.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Military.cpp.o
.PHONY : Military.cpp.o

Military.i: Military.cpp.i

.PHONY : Military.i

# target to preprocess a source file
Military.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Military.cpp.i
.PHONY : Military.cpp.i

Military.s: Military.cpp.s

.PHONY : Military.s

# target to generate assembly for a file
Military.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Military.cpp.s
.PHONY : Military.cpp.s

Owner.o: Owner.cpp.o

.PHONY : Owner.o

# target to build an object file
Owner.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Owner.cpp.o
.PHONY : Owner.cpp.o

Owner.i: Owner.cpp.i

.PHONY : Owner.i

# target to preprocess a source file
Owner.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Owner.cpp.i
.PHONY : Owner.cpp.i

Owner.s: Owner.cpp.s

.PHONY : Owner.s

# target to generate assembly for a file
Owner.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Owner.cpp.s
.PHONY : Owner.cpp.s

Painter.o: Painter.cpp.o

.PHONY : Painter.o

# target to build an object file
Painter.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Painter.cpp.o
.PHONY : Painter.cpp.o

Painter.i: Painter.cpp.i

.PHONY : Painter.i

# target to preprocess a source file
Painter.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Painter.cpp.i
.PHONY : Painter.cpp.i

Painter.s: Painter.cpp.s

.PHONY : Painter.s

# target to generate assembly for a file
Painter.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Painter.cpp.s
.PHONY : Painter.cpp.s

PeopleVehicle.o: PeopleVehicle.cpp.o

.PHONY : PeopleVehicle.o

# target to build an object file
PeopleVehicle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/PeopleVehicle.cpp.o
.PHONY : PeopleVehicle.cpp.o

PeopleVehicle.i: PeopleVehicle.cpp.i

.PHONY : PeopleVehicle.i

# target to preprocess a source file
PeopleVehicle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/PeopleVehicle.cpp.i
.PHONY : PeopleVehicle.cpp.i

PeopleVehicle.s: PeopleVehicle.cpp.s

.PHONY : PeopleVehicle.s

# target to generate assembly for a file
PeopleVehicle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/PeopleVehicle.cpp.s
.PHONY : PeopleVehicle.cpp.s

Person.o: Person.cpp.o

.PHONY : Person.o

# target to build an object file
Person.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Person.cpp.o
.PHONY : Person.cpp.o

Person.i: Person.cpp.i

.PHONY : Person.i

# target to preprocess a source file
Person.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Person.cpp.i
.PHONY : Person.cpp.i

Person.s: Person.cpp.s

.PHONY : Person.s

# target to generate assembly for a file
Person.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Person.cpp.s
.PHONY : Person.cpp.s

Rickshaw.o: Rickshaw.cpp.o

.PHONY : Rickshaw.o

# target to build an object file
Rickshaw.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Rickshaw.cpp.o
.PHONY : Rickshaw.cpp.o

Rickshaw.i: Rickshaw.cpp.i

.PHONY : Rickshaw.i

# target to preprocess a source file
Rickshaw.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Rickshaw.cpp.i
.PHONY : Rickshaw.cpp.i

Rickshaw.s: Rickshaw.cpp.s

.PHONY : Rickshaw.s

# target to generate assembly for a file
Rickshaw.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Rickshaw.cpp.s
.PHONY : Rickshaw.cpp.s

Truck.o: Truck.cpp.o

.PHONY : Truck.o

# target to build an object file
Truck.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Truck.cpp.o
.PHONY : Truck.cpp.o

Truck.i: Truck.cpp.i

.PHONY : Truck.i

# target to preprocess a source file
Truck.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Truck.cpp.i
.PHONY : Truck.cpp.i

Truck.s: Truck.cpp.s

.PHONY : Truck.s

# target to generate assembly for a file
Truck.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Truck.cpp.s
.PHONY : Truck.cpp.s

Vehicle.o: Vehicle.cpp.o

.PHONY : Vehicle.o

# target to build an object file
Vehicle.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Vehicle.cpp.o
.PHONY : Vehicle.cpp.o

Vehicle.i: Vehicle.cpp.i

.PHONY : Vehicle.i

# target to preprocess a source file
Vehicle.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Vehicle.cpp.i
.PHONY : Vehicle.cpp.i

Vehicle.s: Vehicle.cpp.s

.PHONY : Vehicle.s

# target to generate assembly for a file
Vehicle.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/Vehicle.cpp.s
.PHONY : Vehicle.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/3prj.dir/build.make CMakeFiles/3prj.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 3prj"
	@echo "... Agricultural.o"
	@echo "... Agricultural.i"
	@echo "... Agricultural.s"
	@echo "... Bus.o"
	@echo "... Bus.i"
	@echo "... Bus.s"
	@echo "... Company.o"
	@echo "... Company.i"
	@echo "... Company.s"
	@echo "... Coownership.o"
	@echo "... Coownership.i"
	@echo "... Coownership.s"
	@echo "... Database.o"
	@echo "... Database.i"
	@echo "... Database.s"
	@echo "... ElectricCar.o"
	@echo "... ElectricCar.i"
	@echo "... ElectricCar.s"
	@echo "... ElectricMotorcycle.o"
	@echo "... ElectricMotorcycle.i"
	@echo "... ElectricMotorcycle.s"
	@echo "... ElectricVehicle.o"
	@echo "... ElectricVehicle.i"
	@echo "... ElectricVehicle.s"
	@echo "... FuelCar.o"
	@echo "... FuelCar.i"
	@echo "... FuelCar.s"
	@echo "... FuelMotorcycle.o"
	@echo "... FuelMotorcycle.i"
	@echo "... FuelMotorcycle.s"
	@echo "... FuelVehicle.o"
	@echo "... FuelVehicle.i"
	@echo "... FuelVehicle.s"
	@echo "... Litter.o"
	@echo "... Litter.i"
	@echo "... Litter.s"
	@echo "... Military.o"
	@echo "... Military.i"
	@echo "... Military.s"
	@echo "... Owner.o"
	@echo "... Owner.i"
	@echo "... Owner.s"
	@echo "... Painter.o"
	@echo "... Painter.i"
	@echo "... Painter.s"
	@echo "... PeopleVehicle.o"
	@echo "... PeopleVehicle.i"
	@echo "... PeopleVehicle.s"
	@echo "... Person.o"
	@echo "... Person.i"
	@echo "... Person.s"
	@echo "... Rickshaw.o"
	@echo "... Rickshaw.i"
	@echo "... Rickshaw.s"
	@echo "... Truck.o"
	@echo "... Truck.i"
	@echo "... Truck.s"
	@echo "... Vehicle.o"
	@echo "... Vehicle.i"
	@echo "... Vehicle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

